[23/Oct/2015 20:23:59] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:23:59] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:23:59] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:00] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 
[23/Oct/2015 20:24:30] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 12, in perfil_administrador
    perfil = comprueba_usuario_administrador(id_usuario)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\utils.py", line 25, in comprueba_usuario_administrador
    logger.debug("util/utils - MÃ©todo comprueba_usuario_administrador: id_usuario " + id_usuario)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 14: ordinal not in range(128)
[23/Oct/2015 20:25:22] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 12, in perfil_administrador
    perfil = comprueba_usuario_administrador(id_usuario)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\utils.py", line 25, in comprueba_usuario_administrador
    logger.debug("util/utils - MÃ©todo comprueba_usuario_administrador: id_usuario " + String(id_usuario))
NameError: global name 'String' is not defined
[23/Oct/2015 20:25:57] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:57] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:57] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:57] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:57] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:58] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:58] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:58] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:58] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:58] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[23/Oct/2015 20:25:58] DEBUG [Core.utils:25] util/utils - Método comprueba_usuario_administrador: id_usuario 1
[24/Oct/2015 18:48:06] DEBUG [Core.views.administracion.partidos.views:224] administracion/partidos - Método crear_partido_ajax. 
[24/Oct/2015 18:50:45] DEBUG [Core.views.administracion.partidos.views:224] administracion/partidos - Método crear_partido_ajax. 
[24/Oct/2015 19:20:43] ERROR [django.request:226] Internal Server Error: /guardar_administracion
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 117, in guardar_administracion
    logger.debug("administracion/administracion - MÃ©todo guardar_administracion: id_usuario " + str(id_usuario) + ", accion: " + accion)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
[24/Oct/2015 19:25:42] ERROR [django.request:226] Internal Server Error: /guardar_administracion
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 117, in guardar_administracion
    logger.debug("administracion/administracion - MÃ©todo guardar_administracion: id_usuario " + str(id_usuario) + ", accion: " + accion)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
[24/Oct/2015 19:27:33] ERROR [django.request:226] Internal Server Error: /guardar_administracion
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 117, in guardar_administracion
    logger.debug("administracion/administracion - MÃ©todo guardar_administracion: id_usuario " + str(id_usuario) + ", accion: " + accion + ". " + e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
[24/Oct/2015 19:30:13] ERROR [django.request:226] Internal Server Error: /guardar_administracion
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 120, in guardar_administracion
    logger.debug("administracion/administracion - MÃ©todo guardar_administracion: id_usuario " + str(id_usuario) + ", accion: " + accion + ". " + e)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 33: ordinal not in range(128)
[27/Oct/2015 21:16:08] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 40, in administracion_club
    horas = cargar_horas()
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 164, in cargar_horas
    datetime.time(8, 00),
TypeError: descriptor 'time' requires a 'datetime.datetime' object but received a 'int'
[27/Oct/2015 21:16:09] WARNING [django.request:145] Not Found: /favicon.ico
[27/Oct/2015 21:16:09] WARNING [django.request:145] Not Found: /favicon.ico
[27/Oct/2015 21:20:35] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 40, in administracion_club
    horas = cargar_horas()
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 164, in cargar_horas
    datetime.time(8, 00, 00),
TypeError: descriptor 'time' requires a 'datetime.datetime' object but received a 'int'
[27/Oct/2015 21:20:57] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 40, in administracion_club
    horas = cargar_horas()
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 164, in cargar_horas
    datetime.time(8, 00, 00),
TypeError: descriptor 'time' requires a 'datetime.datetime' object but received a 'int'
[27/Oct/2015 21:21:27] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 40, in administracion_club
    horas = cargar_horas()
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 163, in cargar_horas
    t = datetime.time(8,0,0)
TypeError: descriptor 'time' requires a 'datetime.datetime' object but received a 'int'
[01/Nov/2015 11:30:33] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 40, in administracion_club
    horas = cargar_horas()
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 164, in cargar_horas
    datetime.time(8, 00, 00),
TypeError: descriptor 'time' requires a 'datetime.datetime' object but received a 'int'
[01/Nov/2015 11:30:34] WARNING [django.request:145] Not Found: /favicon.ico
[01/Nov/2015 11:30:34] WARNING [django.request:145] Not Found: /favicon.ico
[01/Nov/2015 11:51:55] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 46, in administracion_club
    return render_to_response(ruta_administracion_club, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 254, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' == fh.inicio.hour' from 'hora == fh.inicio.hour'
[01/Nov/2015 11:52:03] ERROR [django.request:226] Internal Server Error: /administrador/1/club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 46, in administracion_club
    return render_to_response(ruta_administracion_club, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 254, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: ' == fh.inicio.hour' from 'hora == fh.inicio.hour'
[01/Nov/2015 15:32:49] ERROR [django.request:226] Internal Server Error: /guardar_franja_horaria
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administracion\views.py", line 185, in guardar_franja_horaria_ajax
    return HttpResponse(json.dumps(data))
NameError: global name 'json' is not defined
[01/Nov/2015 16:04:31] DEBUG [Core.views.administracion.administracion.views:183] administracion/administracion - Método guardar_franja_horaria_ajax: 
[01/Nov/2015 17:12:13] DEBUG [Core.views.administracion.administracion.views:183] administracion/administracion - Método guardar_franja_horaria_ajax: 
[01/Nov/2015 18:15:46] DEBUG [Core.views.administracion.administracion.views:188] administracion/administracion - Método guardar_franja_horaria_ajax: 
[01/Nov/2015 18:16:28] DEBUG [Core.views.administracion.administracion.views:188] administracion/administracion - Método guardar_franja_horaria_ajax: 
[01/Nov/2015 18:21:37] DEBUG [Core.views.administracion.administracion.views:195] administracion/administracion - Método guardar_franja_horaria_ajax: 
[01/Nov/2015 18:22:53] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[27/Nov/2015 18:40:03] DEBUG [Core.views.administracion.administracion.views:236] administracion/administracion - Método es_inicio_menor_que_fin
[27/Nov/2015 18:40:03] DEBUG [Core.views.administracion.administracion.views:196] administracion/administracion - Método guardar_franja_horaria_ajax: 
[27/Nov/2015 18:45:28] DEBUG [Core.views.administracion.administracion.views:236] administracion/administracion - Método es_inicio_menor_que_fin
[27/Nov/2015 18:45:28] DEBUG [Core.views.administracion.administracion.views:196] administracion/administracion - Método guardar_franja_horaria_ajax: 
[27/Nov/2015 19:41:15] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[27/Nov/2015 19:42:27] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[27/Nov/2015 19:44:17] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[27/Nov/2015 19:45:42] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[27/Nov/2015 19:46:50] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[29/Nov/2015 12:59:43] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[29/Nov/2015 13:01:24] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/club
[29/Nov/2015 13:03:16] DEBUG [Core.views.administracion.administracion.views:243] administracion/administracion - Método es_inicio_menor_que_fin
[29/Nov/2015 13:03:16] DEBUG [Core.views.administracion.administracion.views:203] administracion/administracion - Método guardar_franja_horaria_ajax: 
[29/Nov/2015 13:24:18] DEBUG [Core.views.administracion.administracion.views:243] administracion/administracion - Método es_inicio_menor_que_fin
[29/Nov/2015 13:24:18] DEBUG [Core.views.administracion.administracion.views:203] administracion/administracion - Método guardar_franja_horaria_ajax: 
[29/Nov/2015 18:17:16] DEBUG [Core.views.administracion.administracion.views:246] administracion/administracion - Método guardar_nivel_juego_ajax: 
[29/Nov/2015 18:17:52] DEBUG [Core.views.administracion.administracion.views:246] administracion/administracion - Método guardar_nivel_juego_ajax: 
[29/Nov/2015 18:51:45] WARNING [django.request:145] Not Found: /accounts/login/
[29/Nov/2015 18:51:45] WARNING [django.request:145] Not Found: /favicon.ico
[29/Nov/2015 18:51:45] WARNING [django.request:145] Not Found: /favicon.ico
[29/Nov/2015 19:13:38] WARNING [django.request:145] Not Found: /media/
[04/Dec/2015 19:54:08] ERROR [django.request:226] Internal Server Error: /usuario/2/cuenta
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\usuarios\usuarios_cuenta\views.py", line 48, in usuario_mi_cuenta
    logger.debug("usuarios/cuenta - MÃ©todo usuario_mi_cuenta. id_usuario " + str(id_usuario) +". " + e)
TypeError: cannot concatenate 'str' and 'exceptions.AttributeError' objects
[04/Dec/2015 19:54:09] WARNING [django.request:145] Not Found: /favicon.ico
[04/Dec/2015 19:54:09] WARNING [django.request:145] Not Found: /favicon.ico
[04/Dec/2015 20:00:58] DEBUG [Core.views.usuarios.usuarios_cuenta.views:48] usuarios/cuenta - Método usuario_mi_cuenta. id_usuario 2. 'QuerySet' object has no attribute 'user'
[04/Dec/2015 20:01:49] DEBUG [Core.views.usuarios.usuarios_cuenta.views:48] usuarios/cuenta - Método usuario_mi_cuenta. id_usuario 2. 'QuerySet' object has no attribute 'user'
[04/Dec/2015 20:02:23] DEBUG [Core.views.usuarios.usuarios_cuenta.views:48] usuarios/cuenta - Método usuario_mi_cuenta. id_usuario 2. 'QuerySet' object has no attribute 'user'
[04/Dec/2015 20:04:03] DEBUG [Core.views.usuarios.usuarios_cuenta.views:48] usuarios/cuenta - Método usuario_mi_cuenta. id_usuario 2. 'QuerySet' object has no attribute 'user'
[04/Dec/2015 20:05:29] DEBUG [Core.views.usuarios.usuarios_cuenta.views:48] usuarios/cuenta - Método usuario_mi_cuenta. id_usuario 2. 'QuerySet' object has no attribute 'user'
[04/Dec/2015 20:14:59] ERROR [django.request:226] Internal Server Error: /administrador/1/cuenta
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\cuenta\views.py", line 44, in administracion_cuenta
    perfil.imagen = formImagen.cleaned_data["imagen"]
AttributeError: 'FormImagen' object has no attribute 'cleaned_data'
[04/Dec/2015 20:16:14] ERROR [django.request:226] Internal Server Error: /administrador/1/cuenta
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\cuenta\views.py", line 44, in administracion_cuenta
    perfil.imagen = formImagen.cleaned_data["imagen"]
AttributeError: 'FormImagen' object has no attribute 'cleaned_data'
[17/Jan/2016 21:14:46] ERROR [django.request:226] Internal Server Error: /administrador/1/jugadores/nuevo
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 77, in administrador_nuevo_jugador
    if niveles.has_key(niveles, nivel.deporte.nombre):
AttributeError: 'Deporte' object has no attribute 'nombre'
[17/Jan/2016 21:14:47] WARNING [django.request:145] Not Found: /favicon.ico
[17/Jan/2016 21:14:47] WARNING [django.request:145] Not Found: /favicon.ico
[17/Jan/2016 21:15:47] ERROR [django.request:226] Internal Server Error: /administrador/1/jugadores/nuevo
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 77, in administrador_nuevo_jugador
    if niveles.has_key(niveles, nivel.deporte.deporte):
TypeError: has_key() takes exactly one argument (2 given)
[17/Jan/2016 21:16:57] ERROR [django.request:226] Internal Server Error: /administrador/1/jugadores/nuevo
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 152, in administrador_nuevo_jugador
    return render_to_response(ruta_administracion_nuevo_jugador, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 276, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 331, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'enfor', expected 'empty' o 'endfor'
[18/Jan/2016 12:16:03] ERROR [django.request:226] Internal Server Error: /administrador/1/jugadores/nuevo
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 133, in administrador_nuevo_jugador
    deportes_ids = Deporte.objects.values_list('column_name', flat=True)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 211, in values_list
    return self.get_queryset().values_list(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 535, in values_list
    _fields=fields)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 849, in _clone
    c._setup_query()
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 992, in _setup_query
    self.query.add_fields(self.field_names, True)
  File "C:\Python27\lib\site-packages\django\db\models\sql\query.py", line 1554, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
FieldError: Cannot resolve keyword 'column_name' into field. Choices are: deporte, id, nivel, num_jugadores, pista_deporte
[18/Jan/2016 12:16:05] WARNING [django.request:145] Not Found: /favicon.ico
[18/Jan/2016 12:16:05] WARNING [django.request:145] Not Found: /favicon.ico
[18/Jan/2016 12:20:20] ERROR [django.request:226] Internal Server Error: /administrador/1/jugadores/nuevo
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 137, in administrador_nuevo_jugador
    nivel = Nivel.objects.get(id = request.POST.get(deporte_id))
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: Nivel matching query does not exist.
[18/Jan/2016 12:48:21] WARNING [django.request:145] Not Found: /administrador/1/administradores
[18/Jan/2016 12:54:00] ERROR [django.request:226] Internal Server Error: /administrador/1/administradores
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 90, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 320, in resolve
    sub_match = pattern.resolve(new_path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 222, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 229, in callback
    self._callback = get_callable(self._callback_str)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 32, in wrapper
    result = func(*args)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 117, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import Core.views.administradores_club. View does not exist in module Core.views.
[18/Jan/2016 12:55:51] ERROR [django.request:226] Internal Server Error: /administrador/1/administradores
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administradores\views.py", line 35, in administradores_club
    return render_to_response(administradores_club, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: <function administradores_club at 0x037365B0>
[18/Jan/2016 12:58:08] WARNING [django.request:145] Not Found: /administrador//jugadores
[20/Jan/2016 10:23:59] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[20/Jan/2016 10:31:01] DEBUG [Core.views.administracion.cuenta.views:53] administracion/cuenta - Método administracion_cuenta: id_usuario 1
[20/Jan/2016 12:02:12] ERROR [django.request:226] Internal Server Error: /administrador/1/administradores
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\administradores\views.py", line 63, in administradores_club
    return render_to_response(ruta_administradores, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 809, in do_for
    nodelist_empty = parser.parse(('endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 276, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 331, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'enfor', expected 'endfor'
[20/Jan/2016 12:02:14] WARNING [django.request:145] Not Found: /favicon.ico
[20/Jan/2016 12:02:14] WARNING [django.request:145] Not Found: /favicon.ico
[20/Jan/2016 12:04:16] WARNING [django.request:99] Forbidden (CSRF token missing or incorrect.): /administrador/1/administradores
[20/Jan/2016 12:13:09] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[20/Jan/2016 12:19:49] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[20/Jan/2016 12:32:42] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[20/Jan/2016 12:33:20] DEBUG [Core.views.administracion.administradores.views:72] administracion/administradores - Método administradores_club: id_usuario 1
[20/Jan/2016 12:36:24] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 10:47:44] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:10:38] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:10:41] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:11:02] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:12:24] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:12:45] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:13:04] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:19:20] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:19:24] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:19:54] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:31:59] ERROR [django.request:226] Internal Server Error: /buscador/clubes/baja
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\usuarios\usuarios_clubes\views.py", line 128, in usuario_club_baja
    logger.debug("usuarios/clubes - MÃ©todo usuario_club_baja." + e)
TypeError: cannot concatenate 'str' and 'FieldError' objects
[21/Jan/2016 11:34:33] ERROR [django.request:226] Internal Server Error: /buscador/clubes/baja
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\usuarios\usuarios_clubes\views.py", line 128, in usuario_club_baja
    logger.debug("usuarios/clubes - MÃ©todo usuario_club_baja." + e)
TypeError: cannot concatenate 'str' and 'exceptions.TypeError' objects
[21/Jan/2016 11:43:03] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:43:10] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:43:19] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:43:21] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:49:07] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:52:22] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:53:06] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:53:10] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:54:52] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:56:20] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:58:27] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 11:58:49] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:01:21] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:02:03] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:02:18] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:02:28] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:03:17] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:04:31] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:06:22] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:06:25] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:06:32] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:06:36] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:07:24] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:12:55] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:12:59] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:13:04] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:14:32] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:17:23] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:17:32] ERROR [django.request:226] Internal Server Error: /baja_jugador_club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 75, in baja_jugador_club
    perfilRolClub = PerfilRolClub.objects.get(perfil__id = perfil_id, club__id=club_id)
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: PerfilRolClub matching query does not exist.
[21/Jan/2016 12:18:12] ERROR [django.request:226] Internal Server Error: /baja_jugador_club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 73, in baja_jugador_club
    PerfilRolClub.objects.get(perfil=perfil, club=club).delete()
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: PerfilRolClub matching query does not exist.
[21/Jan/2016 12:18:38] ERROR [django.request:226] Internal Server Error: /baja_jugador_club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 73, in baja_jugador_club
    PerfilRolClub.objects.get(perfil=perfil, club=club).delete()
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: PerfilRolClub matching query does not exist.
[21/Jan/2016 12:19:07] ERROR [django.request:226] Internal Server Error: /baja_jugador_club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 73, in baja_jugador_club
    PerfilRolClub.objects.get(perfil=perfil, club=club).delete()
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: PerfilRolClub matching query does not exist.
[21/Jan/2016 12:19:07] ERROR [django.request:226] Internal Server Error: /baja_jugador_club
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\jugadores\views.py", line 73, in baja_jugador_club
    PerfilRolClub.objects.get(perfil=perfil, club=club).delete()
  File "C:\Python27\lib\site-packages\django\db\models\manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: PerfilRolClub matching query does not exist.
[21/Jan/2016 12:20:16] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:20:20] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:20:23] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:20:25] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:21:11] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:21:47] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:21:56] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:25:10] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:25:14] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:26:00] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:26:20] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:26:26] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:50:13] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:50:58] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[21/Jan/2016 12:51:52] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[22/Jan/2016 10:53:43] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[22/Jan/2016 11:37:23] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[22/Jan/2016 11:55:28] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[22/Jan/2016 12:00:38] WARNING [django.request:145] Not Found: /administrador/1/administradores
[22/Jan/2016 12:00:38] WARNING [django.request:145] Not Found: /favicon.ico
[22/Jan/2016 12:00:38] WARNING [django.request:145] Not Found: /favicon.ico
[23/Jan/2016 00:32:06] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 29, in perfil_administrador
    id = PerfilRolClub.objects.values_list('club_id', flat=True).get(perfil = perfil, rol_id = settings.ROL_ADMINISTRADOR)
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 310, in get
    (self.model._meta.object_name, num))
MultipleObjectsReturned: get() returned more than one PerfilRolClub -- it returned 2!
[23/Jan/2016 00:32:07] WARNING [django.request:145] Not Found: /favicon.ico
[23/Jan/2016 00:32:07] WARNING [django.request:145] Not Found: /favicon.ico
[23/Jan/2016 00:33:38] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 43, in perfil_administrador
    club = Club.objects.get(id = PerfilRolClub.objects.values_list('club_id', flat=True).get(perfil = perfil, rol_id = settings.ROL_ADMINISTRADOR))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 310, in get
    (self.model._meta.object_name, num))
MultipleObjectsReturned: get() returned more than one PerfilRolClub -- it returned 2!
[23/Jan/2016 00:36:12] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 43, in perfil_administrador
    club = Club.objects.get(id = PerfilRolClub.objects.values_list('club_id', flat=True).get(perfil = perfil, rol_id = settings.ROL_ADMINISTRADOR))
  File "C:\Python27\lib\site-packages\django\db\models\query.py", line 310, in get
    (self.model._meta.object_name, num))
MultipleObjectsReturned: get() returned more than one PerfilRolClub -- it returned 2!
[23/Jan/2016 00:37:15] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 39, in perfil_administrador
    nombre_club_id[c.id] = c.nombre
AttributeError: 'tuple' object has no attribute 'nombre'
[23/Jan/2016 00:39:34] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 53, in perfil_administrador
    jugadores = PerfilRolClub.objects.filter(club = club).order_by("perfil__user__first_name")
NameError: global name 'club' is not defined
[23/Jan/2016 00:56:23] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "C:\Python27\lib\site-packages\django\contrib\sessions\middleware.py", line 38, in process_response
    request.session.save()
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\db.py", line 57, in save
    session_data=self.encode(self._get_session(no_load=must_create)),
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 87, in encode
    serialized = self.serializer().dumps(session_dict)
  File "C:\Python27\lib\site-packages\django\core\signing.py", line 88, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "C:\Python27\lib\json\__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Club: Gonzo Padel> is not JSON serializable
[23/Jan/2016 01:07:56] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "C:\Python27\lib\site-packages\django\contrib\sessions\middleware.py", line 38, in process_response
    request.session.save()
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\db.py", line 57, in save
    session_data=self.encode(self._get_session(no_load=must_create)),
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 87, in encode
    serialized = self.serializer().dumps(session_dict)
  File "C:\Python27\lib\site-packages\django\core\signing.py", line 88, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "C:\Python27\lib\json\__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Club: Gonzo Padel> is not JSON serializable
[23/Jan/2016 01:07:56] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 201, in get_response
    response = middleware_method(request, response)
  File "C:\Python27\lib\site-packages\django\contrib\sessions\middleware.py", line 38, in process_response
    request.session.save()
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\db.py", line 57, in save
    session_data=self.encode(self._get_session(no_load=must_create)),
  File "C:\Python27\lib\site-packages\django\contrib\sessions\backends\base.py", line 87, in encode
    serialized = self.serializer().dumps(session_dict)
  File "C:\Python27\lib\site-packages\django\core\signing.py", line 88, in dumps
    return json.dumps(obj, separators=(',', ':')).encode('latin-1')
  File "C:\Python27\lib\json\__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Club: Gonzo Padel> is not JSON serializable
[23/Jan/2016 01:12:13] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 90, in get_response
    response = middleware_method(request)
  File "C:\Python27\lib\site-packages\django\middleware\common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in import_module
    __import__(name)
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 4.0.4\helpers\pydev\_pydev_imps\_pydev_pluginbase.py", line 452, in plugin_import
    fromlist, level)
  File "C:/SportManagement/01 - Proyecto/SportManagement\SportManagement\urls.py", line 11, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 253, in urls
    return self.get_urls(), self.app_name, self.name
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 211, in get_urls
    self.check_dependencies()
  File "C:\Python27\lib\site-packages\django\contrib\admin\sites.py", line 163, in check_dependencies
    raise ImproperlyConfigured("Put 'django.contrib.auth.context_processors.auth' "
ImproperlyConfigured: Put 'django.contrib.auth.context_processors.auth' in your TEMPLATE_CONTEXT_PROCESSORS setting in order to use the admin application.
[23/Jan/2016 01:14:11] WARNING [django.request:145] Not Found: /administrador/css/application.css
[23/Jan/2016 01:14:11] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/font-awesome/css/font-awesome.min.css
[23/Jan/2016 01:14:11] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/css/bootstrap.min.css
[23/Jan/2016 01:14:11] WARNING [django.request:145] Not Found: /administrador/admin/dist/css/sb-admin-2.css
[23/Jan/2016 01:14:11] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.css
[23/Jan/2016 01:14:11] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.css
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.css
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/jquery/dist/jquery.min.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 01:14:12] WARNING [django.request:145] Not Found: /administrador/img/favicon.png
[23/Jan/2016 01:14:13] WARNING [django.request:145] Not Found: /administrador/img/favicon.png
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/dist/css/sb-admin-2.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/css/application.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/font-awesome/css/font-awesome.min.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/css/bootstrap.min.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.css
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/jquery/dist/jquery.min.js
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:15:04] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:15:05] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:15:05] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:15:05] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 01:15:05] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/jquery/dist/jquery.min.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:15:08] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/css/bootstrap.min.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/css/application.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/font-awesome/css/font-awesome.min.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/dist/css/sb-admin-2.css
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/jquery/dist/jquery.min.js
[23/Jan/2016 01:15:45] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:15:47] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:15:47] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:15:47] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 01:15:47] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/jquery/dist/jquery.min.js
[23/Jan/2016 01:15:47] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:15:47] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:15:48] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:15:48] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:15:48] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:15:48] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:15:48] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 01:18:48] WARNING [django.request:145] Not Found: /administrador/admin/dist/css/sb-admin-2.css
[23/Jan/2016 01:18:48] WARNING [django.request:145] Not Found: /administrador/css/application.css
[23/Jan/2016 01:18:48] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/css/bootstrap.min.css
[23/Jan/2016 01:18:48] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.css
[23/Jan/2016 01:18:48] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.css
[23/Jan/2016 01:18:48] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/font-awesome/css/font-awesome.min.css
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.css
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/jquery/dist/jquery.min.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 01:18:49] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/bootstrap/dist/js/bootstrap.min.js
[23/Jan/2016 01:18:50] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/metisMenu/dist/metisMenu.min.js
[23/Jan/2016 01:18:50] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/raphael/raphael-min.js
[23/Jan/2016 01:18:50] WARNING [django.request:145] Not Found: /administrador/admin/bower_components/morrisjs/morris.min.js
[23/Jan/2016 01:18:50] WARNING [django.request:145] Not Found: /administrador/admin/dist/js/sb-admin-2.js
[23/Jan/2016 01:18:50] WARNING [django.request:145] Not Found: /administrador/jquery-ui/jquery-ui.js
[23/Jan/2016 01:18:50] WARNING [django.request:145] Not Found: /administrador/js/admin.js
[23/Jan/2016 02:10:29] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 02:12:26] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 02:12:50] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 02:13:07] WARNING [django.request:145] Not Found: /media/
[23/Jan/2016 02:13:27] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 02:16:57] DEBUG [Core.utils:44] util/utils - Método comprueba_usuario_logado_no_administrador: id_usuario 1
[23/Jan/2016 02:17:39] DEBUG [Core.utils:44] util/utils - Método comprueba_usuario_logado_no_administrador: id_usuario 1
[23/Jan/2016 02:21:50] ERROR [django.request:226] Internal Server Error: /usuario/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\usuarios\usuarios_inicio\views.py", line 47, in usuario_inicio
    return render_to_response(ruta_inicio_usuarios, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 941, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 874, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 163, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 174, in translate_token
    return self.create_var(token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 877, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '()' from 'perfil.es_administrador()'
[23/Jan/2016 02:21:53] WARNING [django.request:145] Not Found: /favicon.ico
[23/Jan/2016 02:21:53] WARNING [django.request:145] Not Found: /favicon.ico
[23/Jan/2016 02:41:01] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 92, in perfil_administrador
    return render_to_response(ruta_pagina_principal, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 941, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 874, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 163, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 174, in translate_token
    return self.create_var(token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 877, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 572, in __init__
    self.args_check(filter_name, filter_func, args)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 641, in args_check
    (name, len(nondefs), plen))
TemplateSyntaxError: stringformat requires 1 arguments, 0 provided
[23/Jan/2016 02:43:21] ERROR [django.request:226] Internal Server Error: /administrador/1
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\inicio\views.py", line 92, in perfil_administrador
    return render_to_response(ruta_pagina_principal, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 140, in render
    return self._render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 134, in _render
    return self.nodelist.render(context)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 840, in render
    bit = self.render_node(node, context)
  File "C:\Python27\lib\site-packages\django\template\debug.py", line 78, in render_node
    return node.render(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 941, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 874, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 163, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 174, in translate_token
    return self.create_var(token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 877, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 571, in __init__
    filter_func = parser.find_filter(filter_name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 366, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
TemplateSyntaxError: Invalid filter: 'int'
[23/Jan/2016 02:56:20] WARNING [django.request:145] Not Found: /media/
[23/Jan/2016 03:06:22] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:07:50] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:07:58] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:09:54] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:10:02] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:10:13] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:10:41] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:19:37] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:21:39] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:24:01] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:28:38] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:28:59] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:29:44] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:30:53] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:31:14] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:31:28] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:33:30] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:34:02] ERROR [django.request:226] Internal Server Error: /administrador/1/notificaciones
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:/SportManagement/01 - Proyecto/SportManagement\Core\views\administracion\notificaciones\views.py", line 29, in notificaciones
    return render_to_response(ruta_administracion_notificaciones, data, context_instance=RequestContext(request))
  File "C:\Python27\lib\site-packages\django\shortcuts\__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "C:\Python27\lib\site-packages\django\template\loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 153, in compile_string
    return parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 806, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Python27\lib\site-packages\django\template\base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 941, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 874, in __init__
    super(TemplateIfParser, self).__init__(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 163, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Python27\lib\site-packages\django\template\smartif.py", line 174, in translate_token
    return self.create_var(token)
  File "C:\Python27\lib\site-packages\django\template\defaulttags.py", line 877, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 360, in compile_filter
    return FilterExpression(token, self)
  File "C:\Python27\lib\site-packages\django\template\base.py", line 577, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '(n.inscripcionEnPartido' from '(n.inscripcionEnPartido'
[23/Jan/2016 03:34:27] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:35:53] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:36:25] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:38:07] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:39:14] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:39:19] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:39:28] WARNING [django.request:145] Not Found: /media/Imagenes/IMG-20130616-WA0008_1.jpg
[23/Jan/2016 03:50:54] DEBUG [Core.views.administracion.administradores.views:82] administracion/administradores - Método administradores_club: id_usuario 1
[23/Jan/2016 03:54:47] DEBUG [Core.views.administracion.administradores.views:84] administracion/administradores - Método administradores_club: id_usuario 1
[23/Jan/2016 03:55:42] DEBUG [Core.views.administracion.administradores.views:84] administracion/administradores - Método administradores_club: id_usuario 1
